### PR TITLE
Fixes Issue #6 and #7

### PR DESCRIPTION
**Pull request by tdfranklin**
How do these look?  Any suggestions before I merge in?

### CODE REVIEW

**Comment by tdfranklin** [comment]
Uh oh... CI failing again... we might have to look into this sooner rather than later.

**Comment by tdfranklin** [comment]
Yes, I believe they would... and you're right, it's very redundant... I just wanted to make it look a little nicer, lol.  I'm going to remove the title of both forms.  Any other ideas or questions I should add?

**Comment by tdfranklin** [comment]
Well @stevenpeniche at least tests passed this time! lol

**Review by stevenpeniche — APPROVED** [review]
Good to go!

**Pull request merged**
