### PR TITLE
config file refactored

### PR DESCRIPTION
**Pull request by tdfranklin**
Ok, so I think I have `napp setup` properly refactored.  Sorry, it took me longer than expected because I couldn't settle on how I wanted to save everything, but I think this will work well.  I did decide to keep everything in a single config file since I think that will make things easier to troubleshoot, we won't have to save a bunch of config files on the user's machine, and also the user will be able to open the config file and add/edit data manually or share that file with other's.

In any case, all I've done so far is get `napp setup` working on the "front-end."  I haven't actually refactored create-component or hooked the config file into that yet.  Before I dive into that, I wanted you to see what I've done so far and get your input to see if you had any suggestions or thoughts before we proceeded?

Also, while I've been trying to go back and update your tests when I change file names, I'm pretty sure I'm breaking a lot of the tests and probably many more will need to be written to test the new functionality.  I apologize in advance, but I think this will set us up for all the future additions we will want for Newton's Apple.  Look forward to hearing your thoughts!

### CODE REVIEW

**Comment by stevenpeniche** [comment]
Great job with the re-vamped initialization process!

As far as the tests are concerned, I opened up CircleCI and noticed that both tests are failing because of a **syntax error** in **configstore.js**.  
```    
/home/circleci/repo/bin/configstore.js:50
            ...projects,
            ^^^
SyntaxError: Unexpected token ...
```
The reason for that is... the current version of **node** that we have specified in **.circleci** is  **7.10**, which doesn't support using the **spread operator** on objects. I believe any **node** version **>=8.6.0**  would work as per this [compatibility chart](http://node.green/#ESNEXT-candidate--stage-3--object-rest-spread-properties). Everything else looks great so if bumping the version works, you have my OK to proceed.

**Review by stevenpeniche — APPROVED** [review]

**Review by stevenpeniche — APPROVED** [review]

**Comment by tdfranklin** [comment]
Good call on the version!  Updated and tests are now passing again, yay!

And glad to hear everything seems alright to you with the coding.  Would you like me to go ahead and merge this into next-release so you can start working on the tests for the front-end, or would you prefer me to wait until I've completed the changes for the back-end create-component refactor before merging?

**Comment by stevenpeniche** [comment]
I'll wait until you've completed the rest of the changes.

**Comment by tdfranklin** [comment]
@stevenpeniche 

Ok, I think I'm done with all the actual code changes.  Take a look when you get time and let me know what you think or if you have any suggestions on a better way to organize going forward.  Before I merge, though, I want to do some major update to the docs to get setup for a more readable format.  So I'll be working on that next.  If you see anything that needs to be changed or have any opinions on how to improve the code, just post it on here and we can discuss.  Thanks for all your help!

**Comment by stevenpeniche** [comment]
Looks great! I was going to mention that `createFile` should be it’s own file but I assume you left it in there because I’ve already extrapolated it over on my fork.

Once you’re done with those doc updates you should be ok to merge. When that’s done I’ll go ahead and restructure my PR accordingly. 👍🏽

**Comment by tdfranklin** [comment]
Ok, I think I'm finished with the docs @stevenpeniche 

Going to go ahead and merge this in shortly, but wanted to give you a chance to glance at it and see if there was anything that needed to be changed first?

**Comment by stevenpeniche** [comment]
I love the separation of Usage, Configuartion and Lifecycle Methods documentation. Greate job guiding new users through the various processes!

**Pull request merged**
